insert into geotree (parent,id,name) values (0,1,'World'); 
insert into geotree (parent,id,name) values (1,2,'Africa');
       insert into geotree (parent,id,name) values (2,8,'Eastern Africa');
       insert into geotree (parent,id,name) values (2,9,'Middle Africa');
       insert into geotree (parent,id,name) values (2,10,'Northern Africa');
       insert into geotree (parent,id,name) values (2,11,'Southern Africa');
       insert into geotree (parent,id,name) values (2,12,'Western Africa');
insert into geotree (parent,id,name) values (1,3,'Latin America and the Caribbean');
       insert into geotree (parent,id,name) values (3,13,'Caribbean');
       insert into geotree (parent,id,name) values (3,14,'Central America');
       insert into geotree (parent,id,name) values (3,15,'South America');
insert into geotree (parent,id,name) values (1,4,'Northern America');
insert into geotree (parent,id,name) values (1,5,'Asia');
       insert into geotree (parent,id,name) values (5,16,'Central Asia');
       insert into geotree (parent,id,name) values (5,17,'Eastern Asia');
       insert into geotree (parent,id,name) values (5,18,'Southern Asia');
       insert into geotree (parent,id,name) values (5,19,'South-Eastern Asia');
       insert into geotree (parent,id,name) values (5,20,'Western Asia');
insert into geotree (parent,id,name) values (1,6,'Europe');
       insert into geotree (parent,id,name) values (6,21,'Eastern Europe');
       insert into geotree (parent,id,name) values (6,22,'Northern Europe');
       insert into geotree (parent,id,name) values (6,23,'Southern Europe');
       insert into geotree (parent,id,name) values (6,24,'Western Europe');
insert into geotree (parent,id,name) values (1,7,'Oceania');
       insert into geotree (parent,id,name) values (7,25,'Australia and New Zealand');
       insert into geotree (parent,id,name) values (7,26,'Melanesia');
       insert into geotree (parent,id,name) values (7,27,'Micronesia');
       insert into geotree (parent,id,name) values (7,28,'Polynesia');
 
insert into geotree (parent,name) values (8,'Burundi');
insert into geotree (parent,name) values (8,'Comoros');
insert into geotree (parent,name) values (8,'Djibouti');
insert into geotree (parent,name) values (8,'Eritrea');
insert into geotree (parent,name) values (8,'Ethiopia');
insert into geotree (parent,name) values (8,'Kenya');
insert into geotree (parent,name) values (8,'Madagascar');
insert into geotree (parent,name) values (8,'Malawi');
insert into geotree (parent,name) values (8,'Mauritius');
insert into geotree (parent,name) values (8,'Mozambique');
insert into geotree (parent,name) values (8,'Réunion');
insert into geotree (parent,name) values (8,'Rwanda');
insert into geotree (parent,name) values (8,'Seychelles');
insert into geotree (parent,name) values (8,'Somalia');
insert into geotree (parent,name) values (8,'Uganda');
insert into geotree (parent,name) values (8,'United Republic of Tanzania');
insert into geotree (parent,name) values (8,'Zambia');
insert into geotree (parent,name) values (8,'Zimbabwe');

insert into geotree (parent,name) values (9,'Angola');
insert into geotree (parent,name) values (9,'Cameroon');
insert into geotree (parent,name) values (9,'Central African Republic');
insert into geotree (parent,name) values (9,'Chad');
insert into geotree (parent,name) values (9,'Congo');
insert into geotree (parent,name) values (9,'Democratic Republic of the Congo');
insert into geotree (parent,name) values (9,'Equatorial Guinea');
insert into geotree (parent,name) values (9,'Gabon');
insert into geotree (parent,name) values (9,'Sao Tome and Principe');

insert into geotree (parent,name) values (10,'Algeria');
insert into geotree (parent,name) values (10,'Egypt');
insert into geotree (parent,name) values (10,'Libya');
insert into geotree (parent,name) values (10,'Morocco');
insert into geotree (parent,name) values (10,'South Sudan');
insert into geotree (parent,name) values (10,'Sudan');
insert into geotree (parent,name) values (10,'Tunisia');
insert into geotree (parent,name) values (10,'Western Sahara');

insert into geotree (parent,name) values (11,'Botswana');
insert into geotree (parent,name) values (11,'Lesotho');
insert into geotree (parent,name) values (11,'Namibia');
insert into geotree (parent,name) values (11,'South Africa');
insert into geotree (parent,name) values (11,'Swaziland');

insert into geotree (parent,name) values (12,'Benin');
insert into geotree (parent,name) values (12,'Burkina Faso');
insert into geotree (parent,name) values (12,'Cape Verde');
insert into geotree (parent,name) values (12,'Cote d\'Ivoire');
insert into geotree (parent,name) values (12,'Gambia');
insert into geotree (parent,name) values (12,'Ghana');
insert into geotree (parent,name) values (12,'Guinea');
insert into geotree (parent,name) values (12,'Guinea-Bissau');
insert into geotree (parent,name) values (12,'Liberia');
insert into geotree (parent,name) values (12,'Mali');
insert into geotree (parent,name) values (12,'Mauritania');
insert into geotree (parent,name) values (12,'Niger');
insert into geotree (parent,name) values (12,'Nigeria');
insert into geotree (parent,name) values (12,'Saint Helena');
insert into geotree (parent,name) values (12,'Senegal');
insert into geotree (parent,name) values (12,'Sierra Leone');
insert into geotree (parent,name) values (12,'Togo');
  

insert into geotree (parent,name) values (13,'Caribbean');
insert into geotree (parent,name) values (13,'Anguilla');
insert into geotree (parent,name) values (13,'Antigua and Barbuda');
insert into geotree (parent,name) values (13,'Aruba');
insert into geotree (parent,name) values (13,'Bahamas');
insert into geotree (parent,name) values (13,'Barbados');
insert into geotree (parent,name) values (13,'Bonaire, Saint Eustatius and Saba');
insert into geotree (parent,name) values (13,'British Virgin Islands');
insert into geotree (parent,name) values (13,'Cayman Islands');
insert into geotree (parent,name) values (13,'Cuba');
insert into geotree (parent,name) values (13,'Curaçao');
insert into geotree (parent,name) values (13,'Dominica');
insert into geotree (parent,name) values (13,'Dominican Republic');
insert into geotree (parent,name) values (13,'Grenada');
insert into geotree (parent,name) values (13,'Guadeloupe');
insert into geotree (parent,name) values (13,'Haiti');
insert into geotree (parent,name) values (13,'Jamaica');
insert into geotree (parent,name) values (13,'Martinique');
insert into geotree (parent,name) values (13,'Montserrat');
insert into geotree (parent,name) values (13,'Puerto Rico');
insert into geotree (parent,name) values (13,'Saint-Barthélemy');
insert into geotree (parent,name) values (13,'Saint Kitts and Nevis');
insert into geotree (parent,name) values (13,'Saint Lucia');
insert into geotree (parent,name) values (13,'Saint Martin (French part)');
insert into geotree (parent,name) values (13,'Saint Vincent and the Grenadines');
insert into geotree (parent,name) values (13,'Sint Maarten (Dutch part)');
insert into geotree (parent,name) values (13,'Trinidad and Tobago');
insert into geotree (parent,name) values (13,'Turks and Caicos Islands');
insert into geotree (parent,name) values (13,'United States Virgin Islands');

insert into geotree (parent,name) values (14,'Belize');
insert into geotree (parent,name) values (14,'Costa Rica');
insert into geotree (parent,name) values (14,'El Salvador');
insert into geotree (parent,name) values (14,'Guatemala');
insert into geotree (parent,name) values (14,'Honduras');
insert into geotree (parent,name) values (14,'Mexico');
insert into geotree (parent,name) values (14,'Nicaragua');
insert into geotree (parent,name) values (14,'Panama');

insert into geotree (parent,name) values (15,'Argentina');
insert into geotree (parent,name) values (15,'Bolivia (Plurinational State of)');
insert into geotree (parent,name) values (15,'Brazil');
insert into geotree (parent,name) values (15,'Chile');
insert into geotree (parent,name) values (15,'Colombia');
insert into geotree (parent,name) values (15,'Ecuador');
insert into geotree (parent,name) values (15,'Falkland Islands (Malvinas)');
insert into geotree (parent,name) values (15,'French Guiana');
insert into geotree (parent,name) values (15,'Guyana');
insert into geotree (parent,name) values (15,'Paraguay');
insert into geotree (parent,name) values (15,'Peru');
insert into geotree (parent,name) values (15,'Suriname');
insert into geotree (parent,name) values (15,'Uruguay');
insert into geotree (parent,name) values (15,'Venezuela (Bolivarian Republic of)');

insert into geotree (parent,name) values (4,'Bermuda');
insert into geotree (parent,name) values (4,'Canada');
insert into geotree (parent,name) values (4,'Greenland');
insert into geotree (parent,name) values (4,'Saint Pierre and Miquelon');
insert into geotree (parent,name) values (4,'United States of America');
  

insert into geotree (parent,name) values (16,'Kazakhstan');
insert into geotree (parent,name) values (16,'Kyrgyzstan');
insert into geotree (parent,name) values (16,'Tajikistan');
insert into geotree (parent,name) values (16,'Turkmenistan');
insert into geotree (parent,name) values (16,'Uzbekistan');

insert into geotree (parent,name) values (17,'Eastern Asia');
insert into geotree (parent,name) values (17,'China');
insert into geotree (parent,name) values (17,'China, Hong Kong Special Administrative Region');
insert into geotree (parent,name) values (17,'China, Macao Special Administrative Region');
insert into geotree (parent,name) values (17,'Democratic People\'s Republic of Korea');
insert into geotree (parent,name) values (17,'Japan');
insert into geotree (parent,name) values (17,'Mongolia');
insert into geotree (parent,name) values (17,'Republic of Korea');

insert into geotree (parent,name) values (18,'Afghanistan');
insert into geotree (parent,name) values (18,'Bangladesh');
insert into geotree (parent,name) values (18,'Bhutan');
insert into geotree (parent,name) values (18,'India');
insert into geotree (parent,name) values (18,'Iran (Islamic Republic of)');
insert into geotree (parent,name) values (18,'Maldives');
insert into geotree (parent,name) values (18,'Nepal');
insert into geotree (parent,name) values (18,'Pakistan');
insert into geotree (parent,name) values (18,'Sri Lanka');
  
insert into geotree (parent,name) values (19,'Brunei Darussalam');
insert into geotree (parent,name) values (19,'Cambodia');
insert into geotree (parent,name) values (19,'Indonesia');
insert into geotree (parent,name) values (19,'Lao People\'s Democratic Republic');
insert into geotree (parent,name) values (19,'Malaysia');
insert into geotree (parent,name) values (19,'Myanmar');
insert into geotree (parent,name) values (19,'Philippines');
insert into geotree (parent,name) values (19,'Singapore');
insert into geotree (parent,name) values (19,'Thailand');
insert into geotree (parent,name) values (19,'Timor-Leste');
insert into geotree (parent,name) values (19,'Viet Nam');

insert into geotree (parent,name) values (20,'Western Asia');
insert into geotree (parent,name) values (20,'Armenia');
insert into geotree (parent,name) values (20,'Azerbaijan');
insert into geotree (parent,name) values (20,'Bahrain');
insert into geotree (parent,name) values (20,'Cyprus');
insert into geotree (parent,name) values (20,'Georgia');
insert into geotree (parent,name) values (20,'Iraq');
insert into geotree (parent,name) values (20,'Israel');
insert into geotree (parent,name) values (20,'Jordan');
insert into geotree (parent,name) values (20,'Kuwait');
insert into geotree (parent,name) values (20,'Lebanon');
insert into geotree (parent,name) values (20,'Occupied Palestinian Territory');
insert into geotree (parent,name) values (20,'Oman');
insert into geotree (parent,name) values (20,'Qatar');
insert into geotree (parent,name) values (20,'Saudi Arabia');
insert into geotree (parent,name) values (20,'Syrian Arab Republic');
insert into geotree (parent,name) values (20,'Turkey');
insert into geotree (parent,name) values (20,'United Arab Emirates');
insert into geotree (parent,name) values (20,'Yemen');

  
insert into geotree (parent,name) values (21,'Belarus');
insert into geotree (parent,name) values (21,'Bulgaria');
insert into geotree (parent,name) values (21,'Czech Republic');
insert into geotree (parent,name) values (21,'Hungary');
insert into geotree (parent,name) values (21,'Poland');
insert into geotree (parent,name) values (21,'Republic of Moldova');
insert into geotree (parent,name) values (21,'Romania');
insert into geotree (parent,name) values (21,'Russian Federation');
insert into geotree (parent,name) values (21,'Slovakia');
insert into geotree (parent,name) values (21,'Ukraine');
insert into geotree (parent,name) values (22,'Åland Islands');
insert into geotree (parent,name) values (22,'Channel Islands');
insert into geotree (parent,name) values (22,'Denmark');
insert into geotree (parent,name) values (22,'Estonia');
insert into geotree (parent,name) values (22,'Faeroe Islands');
insert into geotree (parent,name) values (22,'Finland');
insert into geotree (parent,name) values (22,'Guernsey');
insert into geotree (parent,name) values (22,'Iceland');
insert into geotree (parent,name) values (22,'Ireland');
insert into geotree (parent,name) values (22,'Isle of Man');
insert into geotree (parent,name) values (22,'Jersey');
insert into geotree (parent,name) values (22,'Latvia');
insert into geotree (parent,name) values (22,'Lithuania');
insert into geotree (parent,name) values (22,'Norway');
insert into geotree (parent,name) values (22,'Sark');
insert into geotree (parent,name) values (22,'Svalbard and Jan Mayen Islands');
insert into geotree (parent,name) values (22,'Sweden');
insert into geotree (parent,name) values (22,'United Kingdom of Great Britain and Northern Ireland');

insert into geotree (parent,name) values (23,'Albania');
insert into geotree (parent,name) values (23,'Andorra');
insert into geotree (parent,name) values (23,'Bosnia and Herzegovina');
insert into geotree (parent,name) values (23,'Croatia');
insert into geotree (parent,name) values (23,'Gibraltar');
insert into geotree (parent,name) values (23,'Greece');
insert into geotree (parent,name) values (23,'Holy See');
insert into geotree (parent,name) values (23,'Italy');
insert into geotree (parent,name) values (23,'Malta');
insert into geotree (parent,name) values (23,'Montenegro');
insert into geotree (parent,name) values (23,'Portugal');
insert into geotree (parent,name) values (23,'San Marino');
insert into geotree (parent,name) values (23,'Serbia');
insert into geotree (parent,name) values (23,'Slovenia');
insert into geotree (parent,name) values (23,'Spain');
insert into geotree (parent,name) values (23,'The former Yugoslav Republic of Macedonia');

insert into geotree (parent,name) values (24,'Austria');
insert into geotree (parent,name) values (24,'Belgium');
insert into geotree (parent,name) values (24,'France');
insert into geotree (parent,name) values (24,'Germany');
insert into geotree (parent,name) values (24,'Liechtenstein');
insert into geotree (parent,name) values (24,'Luxembourg');
insert into geotree (parent,name) values (24,'Monaco');
insert into geotree (parent,name) values (24,'Netherlands');
insert into geotree (parent,name) values (24,'Switzerland');
  

insert into geotree (parent,name) values (25,'Australia');
insert into geotree (parent,name) values (25,'New Zealand');
insert into geotree (parent,name) values (25,'Norfolk Island');

insert into geotree (parent,name) values (26,'Fiji');
insert into geotree (parent,name) values (26,'New Caledonia');
insert into geotree (parent,name) values (26,'Papua New Guinea');
insert into geotree (parent,name) values (26,'Solomon Islands');
insert into geotree (parent,name) values (26,'Vanuatu');

insert into geotree (parent,name) values (27,'Guam');
insert into geotree (parent,name) values (27,'Kiribati');
insert into geotree (parent,name) values (27,'Marshall Islands');
insert into geotree (parent,name) values (27,'Micronesia (Federated States of)');
insert into geotree (parent,name) values (27,'Nauru');
insert into geotree (parent,name) values (27,'Northern Mariana Islands');
insert into geotree (parent,name) values (27,'Palau');

insert into geotree (parent,name) values (28,'American Samoa');
insert into geotree (parent,name) values (28,'Cook Islands');
insert into geotree (parent,name) values (28,'French Polynesia');
insert into geotree (parent,name) values (28,'Niue');
insert into geotree (parent,name) values (28,'Pitcairn');
insert into geotree (parent,name) values (28,'Samoa');
insert into geotree (parent,name) values (28,'Tokelau');
insert into geotree (parent,name) values (28,'Tonga');
insert into geotree (parent,name) values (28,'Tuvalu');
insert into geotree (parent,name) values (28,'Wallis and Futuna Islands');
